Js 2
devdvorobyev/OTUS_1 pull request #2
Opened 2023-10-01 21:19 UTC by devdvorobyev

2023-10-08 09:52 UTC, nlapshin requested changes
Попробуйте добавить более комплексный пример с разными типами, вложенным подобъектами и массивами(лучше массив примитивов и массив объектов).

Идеальную функцию будет сложно написать действительно, потому что есть ещё Map,Set и прочии интересные типы, но сравнить два массива можно.

Попробуйте реализовать по принципу:
- сравнить наличие двух ключей в объектах, если нет, то можно выбрасывать исключение.
- сравнить типы двух ключей, если не равны, то можно сразу выбрасывать исключение.
- сравнить значнеие двух ключей, тут разные ветки: объект, массив и примитив, у каждого своя логика.

В целом, текущая реализация выглядит неплохо, но есть что доработать и где поправить недочеты.

2023-10-08 09:52 UTC, nlapshin commented on deepEqual/main.js
> +        if(typeof sourceObject[key] != 'object' && !Array.isArray(sourceObject[key]) ){
Используйте здесь и далее строгое сранение ===, без приведения типов.

2023-10-08 09:52 UTC, nlapshin commented on deepEqual/main.js
> +        if(typeof sourceObject[key] != 'object' && !Array.isArray(sourceObject[key]) ){
Просто для примера входные данные, которые посчитаю, что два объекта одинаковые.

```
const obj1 = {
    a: {
        b: '',
    },
};
const obj2 = {
    a: {
        b: 0,
    },
};

2023-10-08 09:52 UTC, nlapshin commented on deepEqual/main.js
> +    for (const key in sourceObject) {
Не забудьте про это условие "Сравниваются собственные итерируемые свойства, без учета прототипа", сейчас, если я ничего не упустил, оно не реализовано.

2023-10-08 11:01 UTC, devdvorobyev commented on deepEqual/main.js
> +        if(typeof sourceObject[key] != 'object' && !Array.isArray(sourceObject[key]) ){
> Используйте здесь и далее строгое сранение ===, без приведения типов.

Попробовал, но не понимаю, почему он считает, что это не !== )

![image](https://github.com/devdvorobyev/OTUS_1/assets/145908187/eee777bf-f375-4d6f-a72f-81be66344df2)

2023-10-09 15:46 UTC, devdvorobyev commented on deepEqual/main.js
> +    for (const key in sourceObject) {
**Сравниваются собственные итерируемые свойства, без учета прототипа**
Не понимаю, он же и сравнивает свойства объекта

2023-10-15 10:16 UTC, merged